apiVersion: apps/v1
kind: Deployment
metadata:
  name:
  namespace: cjarcau
  labels:
    app:
spec:
  replicas: 1
  selector:
    matchLabels:
      app:
  template:
    metadata:
      labels:
        app:
    spec:
      containers:
      - name:
        image: scr4pp/notebook
        env:
        - name: JUPYTER_TOKEN
          valueFrom:
            secretKeyRef:
              name:
              key: jupyter_token
        - name: NOTEBOOK_ID
          valueFrom:
            secretKeyRef:
              name:
              key: notebook_id
        - name: SERVICE_NAME
          valueFrom:
            secretKeyRef:
              name:
              key: service_name
        - name: DATASET_URL
          valueFrom:
            secretKeyRef:
              name:
              key: dataset_url
        - name: SERVICE_PORT
          value: "49153"
        ports:
        - containerPort: 8888
