apiVersion: apps/v1
kind: Deployment
metadata:
  name:
  namespace: cjarcau
  labels:
    app:
spec:
  replicas: 1
  selector:
    matchLabels:
      app:
  template:
    metadata:
      labels:
        app:
    spec:
      containers:
      - name:
        image: scr4pp/notebook
        env:
        - name: NOTEBOOK_ID
          valueFrom:
            secretKeyRef:
              name:
              key: notebook_id
        - name: SERVICE_NAME
          valueFrom:
            secretKeyRef:
              name:
              key: service_name
        - name: DATASET_URL
          valueFrom:
            secretKeyRef:
              name:
              key: dataset_url
        - name: USER_ID
          valueFrom:
            secretKeyRef:
              name:
              key: user_id
        - name: DATASET_USER
          valueFrom:
            secretKeyRef:
              name:
              key: dataset_user
        - name: TARGET_COLUMN
          valueFrom:
            secretKeyRef:
              name:
              key: target_column
        - name: SERVICE_PORT
          value: "49153"
        - name: API
          value: "https://ingress.sedimark.work/balancer/get/object"
        ports:
        - containerPort: 8888
        imagePullPolicy: IfNotPresent
