apiVersion: apps/v1
kind: Deployment
metadata:
  name:
  namespace: cjarcau
  labels:
    app:
spec:
  replicas: 1
  selector:
    matchLabels:
      app:
  template:
    metadata:
      labels:
        app:
    spec:
      containers:
      - name:
        image: scr4pp/notebook
        env:
        - name: NOTEBOOK_ID
          valueFrom:
            secretKeyRef:
              name:
              key: notebook_id
        - name: DATASET_URL
          valueFrom:
            secretKeyRef:
              name:
              key: dataset_url
        - name: USER_ID
          valueFrom:
            secretKeyRef:
              name:
              key: user_id
        - name: DATASET_USER
          valueFrom:
            secretKeyRef:
              name:
              key: dataset_user
        - name: TARGET_COLUMN
          valueFrom:
            secretKeyRef:
              name:
              key: target_column
        - name: MLFLOW_TRACKING_USERNAME
          valueFrom:
            secretKeyRef:
              name:
              key: mlflow_tracking_username
        - name: MLFLOW_TRACKING_PASSWORD
          valueFrom:
            secretKeyRef:
              name:
              key: mlflow_tracking_password
        - name: MODEL_NAME
          valueFrom:
            secretKeyRef:
              name:
              key: model_name
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: mlflow-secret
              key: aws_access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: mlflow-secret
              key: aws_secret_access_key
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret-config
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret-config
              key: password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret-config
              key: database
        - name: MLFLOW_S3_ENDPOINT_URL
          valueFrom:
            secretKeyRef:
              name: mlflow-secret
              key: mlflow_s3_endpoint_url
        - name: MLFLOW_TRACKING_URI
          valueFrom:
            secretKeyRef:
              name: mlflow-secret
              key: mlflow_tracking_uri
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: postgres-secret-config
              key: host
        - name: POSTGRES_PORT
          value: "32102"
        - name: SERVICE_PORT
          value: "49153"
        - name: SERVICE_NAME
          value:
        - name: API
          value:
        ports:
        - containerPort: 8888
        imagePullPolicy: IfNotPresent
