name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Build image
      run: docker build . --file Dockerfile --tag scr4pp/kubernetes-api:latest
    - name: Push Image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: scr4pp/kubernetes-api:latest
